#!/usr/bin/env python
"""Offline sanity check of the SO-100 kinematic chain — no hardware required.

Verifies that placo loads the TCP-patched URDF, that forward kinematics gives a
plausible workspace, and that inverse kinematics round-trips: FK(q) -> pose ->
IK(pose) -> q' should return the joint configuration we started from.

Run:  ./scripts/check_kinematics.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
URDF = REPO / "assets" / "urdf" / "so100" / "so100.urdf"
JOINTS = ["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll"]
TCP_FRAME = "gripper_frame_link"

# Joint limits straight from the SO-100 URDF, in degrees.
LIMITS_DEG = {
    "shoulder_pan": (-114.6, 114.6),
    "shoulder_lift": (0.0, 200.5),
    "elbow_flex": (-180.0, 0.0),
    "wrist_flex": (-143.2, 68.8),
    "wrist_roll": (-180.0, 180.0),
}


def main() -> int:
    from lerobot.model.kinematics import RobotKinematics

    print(f"URDF: {URDF}")
    kin = RobotKinematics(str(URDF), target_frame_name=TCP_FRAME, joint_names=JOINTS)
    print(f"loaded OK, joints={kin.joint_names}, tcp_frame={TCP_FRAME!r}\n")

    print("=" * 68)
    print("FORWARD KINEMATICS — TCP position at representative poses")
    print("=" * 68)
    poses = {
        "all zero": np.zeros(5),
        "home (arm up)": np.array([0.0, 90.0, -90.0, 0.0, 0.0]),
        "reach forward": np.array([0.0, 45.0, -45.0, -45.0, 0.0]),
        "pan +45": np.array([45.0, 90.0, -90.0, 0.0, 0.0]),
    }
    for name, q in poses.items():
        T = kin.forward_kinematics(q)
        p = T[:3, 3]
        print(f"  {name:<16} q={np.array2string(q, precision=1, floatmode='fixed'):<34} "
              f"tcp=({p[0]:+.4f}, {p[1]:+.4f}, {p[2]:+.4f}) m  |p|={np.linalg.norm(p):.4f}")

    print()
    print("=" * 68)
    print("IK ROUND-TRIP — FK(q) -> pose -> IK(pose) -> q'")
    print("=" * 68)
    rng = np.random.default_rng(0)
    lo = np.array([LIMITS_DEG[j][0] for j in JOINTS])
    hi = np.array([LIMITS_DEG[j][1] for j in JOINTS])
    # stay off the limits, where the arm is often near-singular
    lo_s, hi_s = lo + 0.15 * (hi - lo), hi - 0.15 * (hi - lo)

    pos_errs, rot_errs = [], []
    n_trials = 50
    for _ in range(n_trials):
        q_true = rng.uniform(lo_s, hi_s)
        T_target = kin.forward_kinematics(q_true)
        q_seed = np.clip(q_true + rng.normal(0, 5.0, size=5), lo, hi)
        q_sol = kin.inverse_kinematics(q_seed, T_target)
        T_reached = kin.forward_kinematics(np.asarray(q_sol)[:5])

        pos_errs.append(np.linalg.norm(T_reached[:3, 3] - T_target[:3, 3]))
        dR = T_reached[:3, :3].T @ T_target[:3, :3]
        rot_errs.append(abs(np.degrees(np.arccos(np.clip((np.trace(dR) - 1) / 2, -1, 1)))))

    pos_errs = np.array(pos_errs) * 1000  # mm
    rot_errs = np.array(rot_errs)
    print(f"  trials            {n_trials}")
    print(f"  position error    median {np.median(pos_errs):7.4f} mm   "
          f"p95 {np.percentile(pos_errs, 95):7.4f} mm   max {pos_errs.max():7.4f} mm")
    print(f"  rotation error    median {np.median(rot_errs):7.4f} deg  "
          f"p95 {np.percentile(rot_errs, 95):7.4f} deg  max {rot_errs.max():7.4f} deg")

    # A 5-DoF arm cannot hit arbitrary 6-DoF poses, but poses generated by its own
    # FK are reachable by construction, so the round-trip must be tight.
    ok = np.percentile(pos_errs, 95) < 1.0 and np.percentile(rot_errs, 95) < 1.0
    print()
    print(f"RESULT: {'PASS' if ok else 'FAIL'} — IK round-trip "
          f"{'within' if ok else 'exceeds'} 1 mm / 1 deg at p95")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
